Спринт 7, ветка sprint_7-solution-in-file-manager
SnowmanYP/java-kanban pull request #10
Opened 2024-08-06 09:06 UTC by SnowmanYP

Финальный проект седьмого спринта.

2024-08-06 20:50 UTC, andrew-larkin requested changes
Привет! Хорошая работа, новый функционал работает почти как ожидается. Оставил подробные комментарии по коду. Также стоит добавить тестовый класс для FileManager'а.

2024-08-06 20:50 UTC, andrew-larkin commented on src/exception/ManagerSaveException.java
> +public class ManagerSaveException extends Exception {
extends RuntimeException - показываем, что наше кастомное исключение является непроверяемым

2024-08-06 20:50 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +public class FileBackedTaskManager extends InMemoryTaskManager implements TaskManager {
имплементировать TaskManager здесь не нужно, т.к. это уже делает InMemoryTaskManager, от которого мы наследуемся

2024-08-06 20:50 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +    public void save() {
должен быть приватным, т.к. должен вызываться только внутри методов этого класса

2024-08-06 20:50 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +    public Task fromString(String value) {
эти методы парсинга стоит сделать статическими и выделить в отдельный класс, например, CSVFormat. Это разгрузит текущий класс менеджера от доп. логики

2024-08-06 20:50 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +    public static FileBackedTaskManager loadFromFile(File file) {
падает с NullPointerException

2024-08-06 20:50 UTC, andrew-larkin commented on src/manager/FileBackedTaskManager.java
> +}
прикрепляю тестовый скрипт. это распечатки 2 разных менеджеров. сначала один менеджер создает задачи и записывает их в файл, а затем второй менеджер вычитывает их из файла. Успешный результат: распечатки идентичны друг другу:

public static void main(String[] args) throws IOException {
FileBackedTaskManager fileManager = new FileBackedTaskManager(new File("saveTasks2.csv"));
fileManager.createTask(new Task("task1", "Купить автомобиль"));
fileManager.createEpicTask(new Epic("new Epic1", "Новый Эпик"));
fileManager.createSubTask(new SubTask("New Subtask", "Подзадача", 2));
fileManager.createSubTask(new SubTask("New Subtask2", "Подзадача2", 2));

        fileManager.printAllTasks();
        fileManager.printAllEpicTasks();
        fileManager.printAllSubTasks();


        System.out.println("\n\n" + "new" + "\n\n");

        FileBackedTaskManager fileBackedTasksManager = loadFromFile(new File("saveTasks2.csv"));
        fileBackedTasksManager.printAllTasks();
        fileBackedTasksManager.printAllEpicTasks();
        fileBackedTasksManager.printAllSubTasks();

    }

2024-08-06 20:50 UTC, andrew-larkin commented on src/manager/InMemoryTaskManager.java
>          if (subTasks.isEmpty()) System.out.println("Нет задач в списке");
на самом деле, более полезным будет возвращать просто список задач - тогда мы сможем что-то с ними делать. в том числе распечатать

2024-08-06 20:50 UTC, andrew-larkin commented on src/task/Task.java
> +    private TasksType tasksType = TasksType.TASK;
модификаторы доступа должны быть protected - эти поля нужны в полном доступе для классов наследников. также, taskType лучше инициализировать в конструкторе так же как статус

2024-08-06 20:50 UTC, andrew-larkin commented on src/task/SubTask.java
> +    private TasksType tasksType = TasksType.SUBTASK;
да, добавлять не нужно - это поле уже есть в Task

2024-08-07 19:08 UTC, SnowmanYP commented on src/exception/ManagerSaveException.java
> +public class ManagerSaveException extends Exception {
Исправил

2024-08-07 19:08 UTC, SnowmanYP commented on src/manager/FileBackedTaskManager.java
> +public class FileBackedTaskManager extends InMemoryTaskManager implements TaskManager {
Исправил

2024-08-07 19:12 UTC, SnowmanYP commented on src/manager/FileBackedTaskManager.java
> +    public void save() {
Исправил

2024-08-07 19:12 UTC, SnowmanYP commented on src/manager/FileBackedTaskManager.java
> +    public Task fromString(String value) {
Сделано

2024-08-07 19:25 UTC, SnowmanYP commented on src/manager/FileBackedTaskManager.java
> +    public static FileBackedTaskManager loadFromFile(File file) {
Исправил

2024-08-07 19:26 UTC, SnowmanYP commented on src/manager/FileBackedTaskManager.java
> +}
Сделано, скрипт проверен в классе Main

2024-08-07 20:15 UTC, SnowmanYP commented on src/manager/InMemoryTaskManager.java
>          if (subTasks.isEmpty()) System.out.println("Нет задач в списке");
Добавил методы для получения списка

2024-08-07 20:16 UTC, SnowmanYP commented on src/task/Task.java
> +    private TasksType tasksType = TasksType.TASK;
Исправил

2024-08-07 21:52 UTC, SnowmanYP commented on src/task/SubTask.java
> +    private TasksType tasksType = TasksType.SUBTASK;
Исправил

2024-08-08 10:23 UTC, andrew-larkin approved these changes
Отлично, работа принята!

2024-08-10 22:57 UTC, merged