Добавил новую ветку sprint_6-solution
SnowmanYP/java-kanban pull request #6
Opened 2024-07-17 14:12 UTC by SnowmanYP

2024-07-17 19:24 UTC, andrew-larkin requested changes
Привет! Отличная работа! Местами внести небольшие правки и работа будет принята.

2024-07-17 19:24 UTC, andrew-larkin commented on src/manager/InMemoryHistoryManager.java
>      public List<Task> getHistory() {
все работает хорошо, если остается время, то было бы здорово сделать так, чтобы история возвращалась в обратном порядке (т.е. по "свежести" просмотров)

2024-07-17 19:24 UTC, andrew-larkin commented on src/manager/InMemoryHistoryManager.java
>          //проверки 1 если удаляем первый, последний, единственный и т.д.
в 8 строке класса удаляем закомментированную строку

2024-07-17 19:24 UTC, andrew-larkin commented on src/Main.java
>      public static void main(String[] args) {
удаляем весь закомментированный код

2024-07-17 19:24 UTC, andrew-larkin commented on test/managers/InMemoryHistoryManagerTest.java
>      //manager.getHistoryManager().getHistory() - теперь обращается к новой структуре данных.
удаляем

2024-07-18 12:59 UTC, SnowmanYP commented on src/manager/InMemoryHistoryManager.java
>      public List<Task> getHistory() {
Сделано  getHistory(true or false)  true - прямой порядок, false - обратный

2024-07-18 12:59 UTC, SnowmanYP commented on src/manager/InMemoryHistoryManager.java
>          //проверки 1 если удаляем первый, последний, единственный и т.д.
+

2024-07-18 12:59 UTC, SnowmanYP commented on test/managers/InMemoryHistoryManagerTest.java
>      //manager.getHistoryManager().getHistory() - теперь обращается к новой структуре данных.
+

2024-07-18 13:00 UTC, SnowmanYP commented on test/managers/InMemoryHistoryManagerTest.java
>      //manager.getHistoryManager().getHistory() - теперь обращается к новой структуре данных.
Сделано

2024-07-18 13:00 UTC, SnowmanYP commented on src/manager/InMemoryHistoryManager.java
>          //проверки 1 если удаляем первый, последний, единственный и т.д.
Сделано

2024-07-18 13:01 UTC, SnowmanYP commented on src/manager/InMemoryHistoryManager.java
>      public List<Task> getHistory() {
Так же добавлена проверка в тестах на прямой и обратный порядок вывода

2024-07-18 13:03 UTC, SnowmanYP commented
Добавил новый коммит - [a9f4cfd](https://github.com/SnowmanYP/java-kanban/pull/6/commits/a9f4cfd35d452d431338aca7a979d055926843fe) -  "Внес исправления"

2024-07-28 15:32 UTC, merged